### ISSUE TITLE
Installing ikea-tradfri is breaking

### ISSUE THREAD

**Issue by macanjeros** [CliffS/ikea-tradfri#2]
Hi Cliff,

I was trying to install your ikea-tradfri package and install is breaking. I am new with using npm and node js. 
Error I get: "**npm ERR! Failed at the node-aead-crypto@1.0.5 install script**".

I am using x64 windows 10. Do you know what is causing the problem?

**Comment by CliffS** [comment]
> Do you know what is causing the problem?

No but I'll try to find out.

**Comment by AlCalzone** [comment]
I'll need the complete output of `npm install node-aead-crypto` to see whats going on.

**Comment by AlCalzone** [comment]
Ok I forgot to precompile the binaries for `node-aead-crypto@1.0.5`. The fallback build is probably failing because you don't have python installed and configured for building node-gyp packages.

Solution 1: Install windows-build-tools from a command line with administrator rights `npm --add-python-to-path='true' install --global windows-build-tools`, then try again.  
Solution 2: Wait a bit, I just started the precompiling process.

**Comment by AlCalzone** [comment]
Any news?
